## Docker Plex Setup
## Only creates a docker container with plex instance inside
version: '3.3'
services:
  # Plex installation
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    environment:
      - TZ=Pacific/Auckland
      - PLEX_CLAIM="claim-ieSBqw1QueZLjYY1BDxj"
    volumes:
      - ~/.media-config/plex:/config
      - ~/.transcode/temp:/transcode
      - /mnt/videos:/data
    ports:
      - 32400:32400
    restart: unless-stopped