version: "3.6"
services:
  qbittorrent:
    image: "markusmcnugen/qbittorrentvpn"
    container_name: "qbittorrent"
    restart: "unless-stopped"
    privileged: true
    environment:
      - "VPN_ENABLED=yes"
      - "LAN_NETWORK=192.168.1.1/24"
      - "NAME_SERVERS=1.1.1.1"
      - "VIRTUAL_HOST=nathan-duckett.ddns.net"
      - "VIRTUAL_PORT=8080"
      - "TZ=Auckland/Oceania"
    ports:
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - "~/vpnconfig:/config:cached"
      - "/mnt/download/qbittorrent/downloads:/downloads:cached"