version: "3.3"
services:
  qbittorrent:
    image: "markusmcnugen/qbittorrentvpn"
    container_name: "qbittorrent"
    restart: "unless-stopped"
    privileged: true
    environment:
      - "VPN_ENABLED=yes"
      - "LAN_NETWORK=192.168.1.0/24"
      - "NAME_SERVERS=1.1.1.1,8.8.8.8"
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - "~/.media-config/qBittorrent:/config:cached"
      - "/mnt/downloads:/downloads:cached"