version: '3.3'
services: 
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'nathan-duckett.ddns.net'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://nathan-duckett.ddns.net'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'