## Docker Media Center Build
## Requires prerequisite to be installed, and directories to exist before running
## Assumed it was run using media-docker.sh to correctly preconfigure
version: "3.3"
services:
  # Sonarr installation
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ~/.media-config/sonarr:/config
      - /mnt/videos/Television:/tv
      - /mnt/download/qbittorrent/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  # Radarr installation
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ~/.media-config/radarr:/config
      - /mnt/videos/Movies:/movies
      - /mnt/download/qbittorrent/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  # Jackett installation
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - ~/.media-config/jackett:/config
      - /mnt/download/qbittorrent/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
